// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe0TtKFtcNtg2NT4CMuZYBaunh6HTJUmA',
    appId: '1:131335493107:web:b964876ff2e486bf54ae86',
    messagingSenderId: '131335493107',
    projectId: 'streakaura-6d1c4',
    authDomain: 'streakaura-6d1c4.firebaseapp.com',
    storageBucket: 'streakaura-6d1c4.firebasestorage.app',
    measurementId: 'G-Z1TX7LKTY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbL8XUH6LB4RMgV5hm5Ph3UelZjQRNrkU',
    appId: '1:131335493107:android:18236ed496f2f61854ae86',
    messagingSenderId: '131335493107',
    projectId: 'streakaura-6d1c4',
    storageBucket: 'streakaura-6d1c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZgdiBUUKx29LIhZ1Z2aMBlwchV2iMkhM',
    appId: '1:131335493107:ios:5c43b64148d7046e54ae86',
    messagingSenderId: '131335493107',
    projectId: 'streakaura-6d1c4',
    storageBucket: 'streakaura-6d1c4.firebasestorage.app',
    iosBundleId: 'com.example.streakauraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZgdiBUUKx29LIhZ1Z2aMBlwchV2iMkhM',
    appId: '1:131335493107:ios:5c43b64148d7046e54ae86',
    messagingSenderId: '131335493107',
    projectId: 'streakaura-6d1c4',
    storageBucket: 'streakaura-6d1c4.firebasestorage.app',
    iosBundleId: 'com.example.streakauraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe0TtKFtcNtg2NT4CMuZYBaunh6HTJUmA',
    appId: '1:131335493107:web:70e76a91ae3d9b6154ae86',
    messagingSenderId: '131335493107',
    projectId: 'streakaura-6d1c4',
    authDomain: 'streakaura-6d1c4.firebaseapp.com',
    storageBucket: 'streakaura-6d1c4.firebasestorage.app',
    measurementId: 'G-8G4J0M91QX',
  );
}
