import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:purchases_flutter/purchases_flutter.dart';
import 'utils/time_of_day_adapter.dart';
import 'app.dart';
import 'core/constants/app_constants.dart';
import 'data/models/habit_model.dart';
import 'services/notification_service.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Hive
  await Hive.initFlutter();
  // HabitAdapter is generated by hive_generator
  // We will assume it's available after running build_runner
  Hive.registerAdapter(HabitAdapter()); 
  Hive.registerAdapter(TimeOfDayAdapter());
  await Hive.openBox<Habit>(AppConstants.habitsBox);
  await Hive.openBox(AppConstants.settingsBox);
  
  // Initialize Firebase
  // NOTE: Firebase initialization is commented out as firebase_options.dart is missing.
  // await Firebase.initializeApp();
  
  // Initialize RevenueCat with error handling
  try {
    // TODO: Replace with actual RevenueCat public API key
    await Purchases.configure(PurchasesConfiguration("public_revenuecat_key"));
  } catch (e) {
    // RevenueCat initialization failed - app can still work without payments
    debugPrint('RevenueCat initialization failed: $e');
  }
  
  // Initialize Local Notifications with error handling
  try {
    await NotificationService.instance.initialize();
  } catch (e) {
    // Notification initialization failed - app can still work
    debugPrint('Notification service initialization failed: $e');
  }
  
  runApp(const ProviderScope(child: StreakAuraApp()));
}
