import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:purchases_flutter/purchases_flutter.dart';
import 'utils/time_of_day_adapter.dart';
import 'app.dart';
import 'core/constants/app_constants.dart';
import 'data/models/habit_model.dart';
import 'data/models/subtask_model.dart';
import 'data/models/tag_model.dart';
import 'data/models/project_model.dart';
import 'services/notification_service.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Hive
  await Hive.initFlutter('streakaura_hive');
  // Adapters are generated by hive_generator
  // Guard registration to avoid duplicates during hot restart
  final habitAdapter = HabitAdapter();
  if (!Hive.isAdapterRegistered(habitAdapter.typeId)) {
    Hive.registerAdapter(habitAdapter);
  }

  final subtaskAdapter = SubtaskAdapter();
  if (!Hive.isAdapterRegistered(subtaskAdapter.typeId)) {
    Hive.registerAdapter(subtaskAdapter);
  }

  final tagAdapter = TagAdapter();
  if (!Hive.isAdapterRegistered(tagAdapter.typeId)) {
    Hive.registerAdapter(tagAdapter);
  }

  final projectAdapter = ProjectAdapter();
  if (!Hive.isAdapterRegistered(projectAdapter.typeId)) {
    Hive.registerAdapter(projectAdapter);
  }

  final timeOfDayAdapter = TimeOfDayAdapter();
  if (!Hive.isAdapterRegistered(timeOfDayAdapter.typeId)) {
    Hive.registerAdapter(timeOfDayAdapter);
  }
  await _openBoxWithRecovery<Habit>(AppConstants.habitsBox);
  await _openBoxWithRecovery(AppConstants.settingsBox);
  await _openBoxWithRecovery<Project>(AppConstants.projectsBox);
  await _openBoxWithRecovery<Tag>(AppConstants.tagsBox);

  // Initialize Firebase
  // NOTE: Firebase initialization is commented out as firebase_options.dart is missing.
  // await Firebase.initializeApp();

  // Initialize RevenueCat with error handling
  try {
    // TODO: Replace with actual RevenueCat public API key
    await Purchases.configure(PurchasesConfiguration("public_revenuecat_key"));
  } catch (e) {
    // RevenueCat initialization failed - app can still work without payments
    debugPrint('RevenueCat initialization failed: $e');
  }

  // Initialize Local Notifications with error handling
  try {
    await NotificationService.instance.initialize();
  } catch (e) {
    // Notification initialization failed - app can still work
    debugPrint('Notification service initialization failed: $e');
  }

  runApp(const ProviderScope(child: StreakAuraApp()));
}

Future<void> _openBoxWithRecovery<T>(String boxName) async {
  Future<Box<T>> open() => Hive.openBox<T>(boxName);

  try {
    final box = await open();
    // Force materialization to detect stale/corrupt entries
    box.values.toList(growable: false);
  } catch (e, stackTrace) {
    debugPrint('Hive box "$boxName" reset due to error: $e');
    debugPrint(stackTrace.toString());

    if (Hive.isBoxOpen(boxName)) {
      await Hive.box(boxName).close();
    }

    await Hive.deleteBoxFromDisk(boxName);
    await open();
  }
}
