import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:hive_flutter/hive_flutter.dart';

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:purchases_flutter/purchases_flutter.dart';
import 'utils/time_of_day_adapter.dart';
import 'app.dart';
import 'core/constants/app_constants.dart';
import 'data/models/habit_model.dart';
import 'firebase_options.dart';
import 'services/notification_service.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Hive
  await Hive.initFlutter();
  // HabitAdapter is generated by hive_generator
  // We will assume it's available after running build_runner
  Hive.registerAdapter(HabitAdapter());
  Hive.registerAdapter(TimeOfDayAdapter());
  await Hive.openBox<Habit>(AppConstants.habitsBox);
  await Hive.openBox(AppConstants.settingsBox);

  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  const revenueCatPublicApiKey = "public_revenuecat_key";
  final supportsRevenueCat =
      !kIsWeb &&
      (defaultTargetPlatform == TargetPlatform.iOS ||
          defaultTargetPlatform == TargetPlatform.android);

  if (supportsRevenueCat) {
    // Initialize RevenueCat with error handling
    try {
      // TODO: Replace with actual RevenueCat public API key
      await Purchases.configure(PurchasesConfiguration(revenueCatPublicApiKey));
    } catch (e) {
      // RevenueCat initialization failed - app can still work without payments
      debugPrint('RevenueCat initialization failed: $e');
    }
  } else {
    debugPrint(
      'Skipping RevenueCat initialization on unsupported platform: '
      '${kIsWeb ? "web" : defaultTargetPlatform.name}',
    );
  }

  // Initialize Local Notifications with error handling
  try {
    await NotificationService.instance.initialize();
  } catch (e) {
    // Notification initialization failed - app can still work
    debugPrint('Notification service initialization failed: $e');
  }

  runApp(const ProviderScope(child: StreakAuraApp()));
}
